### ISSUE TITLE
model shows all 100% but not completing

### ISSUE THREAD

**Issue by mt-digital** [VirtualWatershed/vwadaptor#1]
Not sure exactly what's going on, but it's been like this for many minutes.  I'm running your vwplatform branch locally with my latest master merged in.  I tried refreshing, but it stayed the same.

<img width="1203" alt="screen shot 2015-10-02 at 7 20 54 pm" src="https://cloud.githubusercontent.com/assets/2425472/10261054/cb4785b4-693a-11e5-8bab-a98cc731810d.png">

**Comment by itsrifat** [comment]
Did it happen for only one instance or happening for every instance?

**Comment by mt-digital** [comment]
Ah, sorry dude, just that one.  A new one finished fine.
